version: "3.9"
services:
  app:
    build: .
    image: myapp:latest
    volumes:
      - ./:/app          # bind mount project into container
    env_file:
      - .env
    working_dir: /app
    command: ["python", "main.py"]
